name: Neovim Nightly

on: 
  schedule:
    # Checks daily
    - cron: '17 11 * * *'

jobs:
  TestsOnNightly:
    runs-on: ubuntu-latest
    name: "Tests with Neovim Nightly"
    steps:
    - uses: actions/checkout@v4
    - name: Install asdf & tools
      uses: asdf-vm/actions/install@v2
      with:
        tool_versions: |
          neovim nightly
          nodejs
    - run: npm install -g typescript-language-server typescript
    - name: Run Tests on Nightly Neovim
      run: |
        nvim --version
        ./tests/run.sh
